#!/usr/bin/python3
#directory tree flattener
#unpacks archives and removes unnecessary subdirectory levels
#designed for handling large filesystems
#
#(c) 2013 Michael Enßlin	<michael@ensslin.cc>
#
#gplv3 or higher, no warranty, blah, blubb

from dirtreeflattener.main import main
main()
